export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_TOPICS_LOADING = 'GET_TOPICS_LOADING';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILED = 'GET_TOPICS_FAILED';

export const CREATE_TOPIC_LOADING = 'CREATE_TOPIC_LOADING';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_FAILED = 'CREATE_TOPIC_FAILED';

export const CREATE_TOPIC_SET_DEFAULT = 'CREATE_TOPIC_SET_DEFAULT';

export const GET_TOPIC_COMMENTS_LOADING = 'GET_TOPIC_COMMENTS_LOADING';
export const GET_TOPIC_COMMENTS_SUCCESS = 'GET_TOPIC_COMMENTS_SUCCESS';
export const GET_TOPIC_COMMENTS_FAILED = 'GET_TOPIC_COMMENTS_FAILED';

export const CREATE_TOPIC_COMMENT_LOADING = 'CREATE_TOPIC_COMMENT_LOADING';
export const CREATE_TOPIC_COMMENT_SUCCESS = 'CREATE_TOPIC_COMMENT_SUCCESS';
export const CREATE_TOPIC_COMMENT_FAILED = 'CREATE_TOPIC_COMMENT_FAILED';

export const CREATE_COMMENT_SET_DEFAULT = 'CREATE_COMMENT_SET_DEFAULT';
